workflows:
  android-release-apk:
    name: Nizik Android Release APK
    instance_type: linux_x2
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build Android release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  ios-unsigned-ipa:
    name: Nizik Native Unsigned IPA
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build unsigned iOS app
        script: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        script: |
          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -qry Nizik-unsigned.ipa Payload

    artifacts:
      - build/ios/ipa/Nizik-unsigned.ipa
      - build/ios/iphoneos/Runner.app
